name: R Package Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.1.0
          arch: x86_64

      - name: Install dependencies
        run: install.packages(c("devtools", "roxygen2"))

      - name: Create R package
        run: devtools::create("shiny.exe")

      - name: Install R package
        run: devtools::install("shiny.exe")

      - name: Check R package
        run: rcmdcheck("shiny.exe")
